### ISSUE TITLE
problems install

### ISSUE THREAD

**Issue by zechomaru** [mage2/laravel-ecommerce#1]
Hello,
  I am testing the project and the installation there is a problem with the status table. and reviewing the migrations I do not see.

`QueryException in Connection.php line 729:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'field list' (SQL: insert into `order_statuses` (`title`, `status`, `is_default`) values (pending, 1, 1))`

**Comment by indpurvesh** [comment]
@zechomaru  First of all thanks for raising the issue. I have fixed it let me know if you have any problem.

**Comment by zechomaru** [comment]
thanks I'll keep trying and you commented.

**Comment by indpurvesh** [comment]
@zechomaru  i am closing this issue.
