### ISSUE TITLE
Module development (how to)

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#102]
I'm trying to add my first module on this system

But I'm stuck on registering provider `Module.php`

It seems like the only way to add module is to manually register the provider to mage2/ecommerce module.

Is there a proper way to add Module?

**Comment by indpurvesh** [comment]
you can do it inside config/app.php provider section

just use module.php file namespace into config/app.php (Provider section)

    Mage2\ModuleName\Module::class,

I hope this would help.

For autoloading file you can add namespace into composer,json and use

    composer dump-autoload

thanks

**Comment by darron1217** [comment]
Thanks, I'll go for it :)
