### ISSUE TITLE
how to make a correct ajax post request

### ISSUE THREAD

**Issue by vladbuich** [mage2/laravel-ecommerce#103]
need a help to create a correct ajax request. always have an 419 or 500 error. i suppose problem in request url or route
ajax:
`$.ajaxSetup({
           headers: {'X-CSRF-Token': $('meta[name=csrf_token]').attr('content')}
        });
  $.ajax({ 
                  url: "./send-message",
                  type: "POST",
                  data: {
                         "text": text},
                  dataType: "json",
                  success: function(response){
                      alert(response);
                  }
              });`

route:

`Route::middleware(['web','front.auth'])
    ->namespace('Mage2\Ecommerce\Http\Controllers')
    ->group(function () {
Route::post('/my-account/send-message', ['as' => 'chat.send', 'uses' => 'ChatController@send']);}`

`Route::middleware(['web'])
    ->namespace('Mage2\Ecommerce\Http\Controllers')
    ->group(function () {Route::post('/my-account/send-message', ['as' => 'chat.send', 'uses' => 'ChatController@send']);
    });`

controller:

`class ChatController extends Controller
{public function send(Request $request)
    {
        return true;
        $message = $request->get('text');
        $id = Auth::user()->id;
        return chat_message::sendMessage($message, $id);
    }
}`

model:

`class chat_message extends BaseModel
{
public static function sendMessage($text, $id)
    {
        return chat_message::create(['user_id' => $id, 'message' => $text]);
    }
}`

**Comment by indpurvesh** [comment]
I think you perfectly fine except one simple  error.


    $.ajaxSetup({ headers: {'X-CSRF-Token': $('meta[name=csrf-token]').attr('content')} }); 
    $.ajax({ url: "./send-message", 
            type: "POST", 
            data: {  "text": text}, dataType: "json", 
            success: function(response){
                   alert(response);
                } 
           });


$('meta[name=csrf-token]').attr('content') use hypen(-) not underscore (_).

**Comment by vladbuich** [comment]
@indpurvesh you're right , but nevertheless i face with the same error 500 (internal server error)

**Comment by indpurvesh** [comment]
@vladbuich can you put your laravel.log file content here.
    storage/log/laravel.log

If i can see your log it helps me to understand why you getting 500 error. thanks

**Comment by vladbuich** [comment]
[laravel.log](https://github.com/mage2/laravel-ecommerce/files/1541500/laravel.log)

**Comment by indpurvesh** [comment]
@vladbuich seems like some kind a permission issue that's why it causing an 500 error

**Comment by vladbuich** [comment]
@indpurvesh it didn't help. no more idea what to do(

**Comment by vladbuich** [comment]
@indpurvesh how would you do this task?

**Comment by indpurvesh** [comment]
Use google chrome console or inside developers tool.

Try to do dump into first line of controller and make sure route is fine.
Try to change post to get request 
If you have a debug tool setup in your editor that helps too. 

To me it seems some very simple problem.
