### ISSUE TITLE
How to make filter by brand like it presented in demo site?

### ISSUE THREAD

**Issue by Kostyarik** [mage2/laravel-ecommerce#104]
I want to know, whether it preinstalled feature or I need to do it myself?

**Comment by indpurvesh** [comment]
Here is the step to create an Product Specification Attribute:

Login to Admin Panel.
Go to Catalog => Attribute => Create Attribute

Fill out form as: 
Type: Product,
name: Brand
identifier: brand
use as: specification
field type: dropdown
sort Order: 10

create Different Brand brand name as an dropdown options.

Once you go to product Edit on backend. 
You will see Attributes panel(card) it will asked for select brand for the product.

Once you do it then on front end you will see Product Filter

Thanks
Purvesh
