### ISSUE TITLE
Is planned an Omnipay integration?

### ISSUE THREAD

**Issue by tehuel** [mage2/laravel-ecommerce#105]
I've found this ecommerce  solution and really liked it, but the problem is that only Paypal is supported at the moment and Paypal doesn't work well in my country.

Looking for alternatives in payment processing i came across [Omnipay](https://github.com/thephpleague/omnipay), wich aims to be a standarized payment gateway interface.

Is viable to integrate it?

**Comment by indpurvesh** [comment]
Yes you can make any payment gateway modules in here too. I am working on custom module development feature and documentation. 

If it’s so urgent for you in that case I can make a custom payment module for you. With minor cost and if you preferred to do by urself I am more then happy to help you. 

Thanks 
Purvesh
