### ISSUE TITLE
File structure documentation

### ISSUE THREAD

**Issue by ajitdas123** [mage2/laravel-ecommerce#106]
Hi indpurvesh, 
Thank you for this awesome project. 
Btw i want to ask if it is possible to make a readme file along with the file structure for the project. 
I was looking for models controllers routes but those are empty and couldn't find the resource folder too, it took me sometime to find that those are actually under **modules>mage2** 
i also saw some of the same files also in **themes folder** .So still i am not very sure which one actually using 
So, if you could give me little heads up or if you could put file structure to follow would be very helpful.

And one more thing that i would like to ask. How did you make this package as installer. like going to install. it automatically install everything . Is there any tutorial or anything on that? if you could share would be appreciated. 
Thanks again

**Comment by indpurvesh** [comment]
Modules=> mage2  contact the CODE base and Admin Theme(Views) files.
Themes/mage2/default => Frontend theme.

I hope above gives you some idea.

I am just not sure about what you mean by Package as installer?

**Comment by ajitdas123** [comment]
Oh ic. so if i want to make a new theme for the project shall i overwrite the theme file inside Themes/mage2/default or shall i make a new theme folder and if so how do i link it ?

And package installer means. This project of yours is like one click installer  just like wordpress. How did you do that??
I mean to say is. When i loaded the project for the first time and went to this url www.example.com/mage2/install  It install everything automatically. I mean to ask how did you do that? 
I hope i able to explain myself. and sorry this might sound noobies :D
