### ISSUE TITLE
can't add pictures and send email invoices

### ISSUE THREAD

**Issue by vladbuich** [mage2/laravel-ecommerce#107]
i'd like to understand is it my installation problem or it didn't work earlier. And what i need to do to fix it
when i'm trying to change the order status i have this screen. 
<img width="1280" alt="2017-12-18 20 37 19" src="https://user-images.githubusercontent.com/24589835/34114007-57e60048-e433-11e7-8d7a-8f044df76657.png">

also i can't add/load/delete products photos
<img width="580" alt="2017-12-18 20 38 22" src="https://user-images.githubusercontent.com/24589835/34114087-96a9457e-e433-11e7-8872-a8548f3848e7.png">

sorry for so many questions, i really want to improve your project!
thank you in advance!

**Comment by indpurvesh** [comment]
First Error is : Email Setup.

Currently I am using MailTrap

How to Setup: open your .env file

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=YOUR-MAIL-TRAP-USER-ID
MAIL_PASSWORD=YOUR-MAILTRAP-Password

Thanks



Second bug seems to related to Permission issue on public folder.

Try to change public/uploads &  public/vendor folder permission to : 755 or 777

Thanks

**Comment by vladbuich** [comment]
just tried your advices. when i upload an image i have an internal server error on the following line
<img width="699" alt="2017-12-20 20 08 23" src="https://user-images.githubusercontent.com/24589835/34214083-30d78b0c-e5c3-11e7-8088-6a9bc6b8136a.png">

**Comment by vladbuich** [comment]
@indpurvesh I’m using mac.
 Do you think this is a bug? I even can’t understand how the upload method works)) so, I’ll try to fix it too. Thank you for your response!

**Comment by indpurvesh** [comment]
I don't think at this stage its a bug But may be it might be specific to Windows or Mac system because both file system works differently. If you want to give it a try to fix it. 

Please open modules/mage2/ecommerce/Image/Service.php file which contains the upload method. Starting point for you to start debug, 

thanks
P

**Comment by vladbuich** [comment]
@indpurvesh I already deployed it in hosting and got the same error. Don’t think it’s a system problem

**Comment by indpurvesh** [comment]
May be it could be a bug. I will start debug soon. Thanks for raising

**Comment by vladbuich** [comment]
@indpurvesh i found the problem. in service.php when it creates new folder for image, the folder has permission 411 that's why the image can't be loaded
