### ISSUE TITLE
Error adding products.

### ISSUE THREAD

**Issue by smccoy78** [mage2/laravel-ecommerce#108]
When I attempt to add a new product I get the following error:

Error in Saving Product: SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'field list' (SQL: update `products` set `0` = {"id":3,"type":"PRODUCT","name":"AWG","identifier":"awg","use_as":"VARIATION","field_type":"SELECT","sort_order":12,"created_at":"2017-11-15 22:56:34","updated_at":"2017-11-15 22:56:34","pivot":{"product_id":25,"attribute_id":3}}, `updated_at` = 2017-12-18 16:28:29 where `id` = 25)

Error occurs when I create a new product and then attempt to add the product detail information.

**Comment by smccoy78** [comment]
Here is the Post Data.

_token | "4osajlu9czouN3pPttBiVJFuIymLrC7jE93NLHGw"
_method | "put"
name | "Honeywell Thermostat Wire"
category_id | array:1 [▼   0 => "4" ]
slug | "honeywell-thermostat-wire"
sku | "HTW-1000-10"
description | "<p>Honeywell OEM 10 gauge thermostat wire.</p>"
price | "32.09"
status | "1"
qty | "500"
in_stock | "1"
track_stock | "1"
is_taxable | "1"
page_title | ""
page_description | ""
attributes_specification | array:1 [▼   3 => "" ]
attribute_id | array:1 [▼   0 => "3" ]

**Comment by indpurvesh** [comment]
To me it seems like Error is belongs to Product Attribute Save/Update bug. Ideally it should ignore if Attribute Value is not specified. I will take a look at the bug and fixed it soon Thanks for raising.
