### ISSUE TITLE
whats about deals or sales

### ISSUE THREAD

**Issue by ihabhamad** [mage2/laravel-ecommerce#110]
whats about deals or sale or offers not coupons?

**Comment by ihabhamad** [comment]
whats about tags

**Comment by indpurvesh** [comment]
I will implement later on some sales & marketing related feature & Coupon Code.

Product tags features comes as a i hope custom module. Currently I am working on Custom module feature and documantation so once it will be done. I will put it on website.[Mage2 Website](http://mage2.website)

This is not a bug so i will close this issue as of now. thanks @ihabhamad
