### ISSUE TITLE
Checkout Function not working

### ISSUE THREAD

**Issue by llamorinjason** [mage2/laravel-ecommerce#111]
Upon checking out, the order would not be shown to My Orders in the profile. and Lacking some validation upon submit your check out items please fix. Thanks

**Comment by ihabhamad** [comment]
yes Checkout  not working yet but i well fix it soon

**Comment by indpurvesh** [comment]
It should be fixed in master branch 

thanks for raising the bug. @llamorinjason  & @ihabhamad
