### ISSUE TITLE
middlewares on front controller 

### ISSUE THREAD

**Issue by ihabhamad** [mage2/laravel-ecommerce#112]
if you using middleware on front controllers theme well be default mage2 theme not active theme path

**Comment by ihabhamad** [comment]
its working if  middleware extend  Mage2\Ecommerce\Http\Controllers\Controller; but not perfect solution 
{middleware override extends basecontroller }

**Comment by indpurvesh** [comment]
I just done some basic custom theme support.

If you create a new theme on frontend then
active using admin->system->theme then
click on Activated button 

It will load new views file from new themes folder.

**Comment by ihabhamad** [comment]
yes i am create new theme sorry  for wrong  describe problem but in middlewares act as FrontAuth if i actve my new theam and i don't extend Mage2\Ecommerce\Http\Controllers\Controller default theme well be showing on login page if extend Controller work properly 
`class FrontAuth
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure $next
     * @param string|null $guard
     *
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = 'web')
    {
        if (Auth::guard($guard)->guest()) {
            if ($request->ajax() || $request->wantsJson()) {
                return response('Unauthorized.', 401);
            } else {
                return redirect()->guest('/login');
            }
        }

        return $next($request);
    }
}
`
`use Mage2\Ecommerce\Http\Controllers\Controller;

class FrontAuth extends Controller
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure $next
     * @param string|null $guard
     *
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = 'web')
    {
        if (Auth::guard($guard)->guest()) {
            if ($request->ajax() || $request->wantsJson()) {
                return response('Unauthorized.', 401);
            } else {
                return redirect()->guest('/login');
            }
        }

        return $next($request);
    }
}
`
