### ISSUE TITLE
Class frontguest does not exist

### ISSUE THREAD

**Issue by peerrabe** [mage2/laravel-ecommerce#113]
http://demo.mage2.website/password/reset

**Comment by indpurvesh** [comment]
I have fixed it on master branch but once i will update the Demo i will close this issue.

thanks for raise @peerrabe

**Comment by peerrabe** [comment]
ah, as simple as that, thanks

**Comment by indpurvesh** [comment]
I will close this as of now. Possible i will update the demo next week sometimes. Thanks @peerrabe
