### ISSUE TITLE
Bug on viewing  /cart/view

### ISSUE THREAD

**Issue by jbcu10** [mage2/laravel-ecommerce#117]
I receive an error after adding items to cart when I tried to view it

**Exception:**
> ErrorException (E_ERROR)
Route [cart.update] not defined. (View: /Users/johnbenuera/Projects/laravel-ecommerce/themes/mage2/default/views/cart/view.blade.php)

**Arguments:**
`Route [cart.update] not defined. (View: /Users/johnbenuera/Projects/laravel-ecommerce/themes/mage2/default/views/cart/view.blade.php)`
**Code:**
`public function route($name, $parameters = [], $absolute = true)`
    {
       if (! is_null($route = $this->routes->getByName($name)))
       {
            return $this->toRoute($route, $parameters, $absolute);
        }
 
       throw new InvalidArgumentException("Route [{$name}] not defined.");
    }

**Comment by reezooh** [comment]
Hi, there!

There is an error in _routes/web.php_, line 35:

`Route::put('/cart/update', 'CartController@update')
                ->name('cart.updade');`

It should be writen "update" instead.

**Comment by indpurvesh** [comment]
thanks @reezooh

**Comment by jbcu10** [comment]
great, thanks @reezooh
