### ISSUE TITLE
Error! Trying to get property of non-object.

### ISSUE THREAD

**Issue by WESLEY-PEARSON** [mage2/laravel-ecommerce#12]
I get this error in wishlist.my-account.wishlist page:

Trying to get property of non-object

 <td> {{ $wishlist->product->id }}</td>

**Comment by indpurvesh** [comment]
@WESLEY-PEARSON Could you please tell me on which page you get this issue?

**Comment by WESLEY-PEARSON** [comment]
wishlist.my-account.wishlist page.

The system does not recognize product variable.

**Comment by indpurvesh** [comment]
@WESLEY-PEARSON Sorry but i cant replicate the bug. To me it seems like you have:
 created one product -> added into wishlist ->delete product -> now you visiting the wishlist page?

**Comment by WESLEY-PEARSON** [comment]
Yes, I added a product into wishlist and when I visiting the wishlist page I get this error but I think it's due to the fact that the system does not recognize the product because if I delete the product from the instance {{ $wishlist->product->id }} {{ $wishlist->id }}the page opens but obviously without the items of the product.

**Comment by WESLEY-PEARSON** [comment]
I just fixed the problem. It was my typo in class wishlist model. Thank you anyway.

**Comment by indpurvesh** [comment]
@WESLEY-PEARSON  thanks for raising the issue. anyway it remind me adding one feature that i forget it in past.
