### ISSUE TITLE
Address 2 is not required + Terms check is required

### ISSUE THREAD

**Issue by krahamath** [mage2/laravel-ecommerce#121]
On the Checkout page Address 2 is no need to fill. Please remove that from required And Terms checkbox is not showing required error but When submit without check it clear all the values entered in the Personal and Address form.

**Comment by indpurvesh** [comment]
@krahamath should be fixed

**Comment by krahamath** [comment]
Fixed or not ?

**Comment by indpurvesh** [comment]
Fixed

**Comment by krahamath** [comment]
Ok next fixed means please add your commit to check so that it will help to check and help you on this good project.
