### ISSUE TITLE
Can you add skip on Db import

### ISSUE THREAD

**Issue by krahamath** [mage2/laravel-ecommerce#123]
Hi,

Can you add skip on Db import step on installation and Add seed for admin login. Because i did import using run migration but admin details are missing so i must run the db import but that bring me error.

**Comment by indpurvesh** [comment]
fixed to check

**Comment by krahamath** [comment]
I didn’t see any commit and please let me know what is fixed.

**Comment by indpurvesh** [comment]
commit comes in Install module 

https://github.com/mage2/install

**Comment by krahamath** [comment]
Oh ok thank you

**Comment by indpurvesh** [comment]
@krahamath welcome
