### ISSUE TITLE
Upload product image error.

### ISSUE THREAD

**Issue by asnike** [mage2/laravel-ecommerce#125]
Hello. I started to use this package in the first time. Installation is success. 
I connected at the admin page. Uploaded Image file in product creation page. But I faced an error.

`ErrorException: Undefined property: Mage2\Ecommerce\Image\LocalFile::$path`

I guess the problem is this part  - "$image->path->name()" - in the 'upload-image.blade.php' file.
I'm sorry that my English is poor.

**Comment by Steven0811** [comment]
Same here, It's been a long time I can't upload image too.
![screen shot 2018-02-28 at 12 54 14 am](https://user-images.githubusercontent.com/4948562/36742234-1d4a4148-1c22-11e8-8226-53807481990c.png)

**Comment by indpurvesh** [comment]
This should be fixed. Yes @asnike it was the path issue.
