### ISSUE TITLE
Session not reloading properly

### ISSUE THREAD

**Issue by gabrielkolbe** [mage2/laravel-ecommerce#16]
Site worked fine on installation, but next day returning to the site, the session is not reloading properly. This is the error message I get.

ErrorException in Website.php line 50:
Trying to get property of non-object
in Website.php line 50
at HandleExceptions->handleError('8', 'Trying to get property of non-object', 'C:\xampp\htdocs\laravelcommerce\modules\base\Mage2\System\Middleware\Website.php', '50', array('request' => object(Request), 'next' => object(Closure), 'host' => 'laravelcommerce', 'cacheKey' => 'default_website_middleware_query', 'website' => null, 'minute' => '100')) in Website.php line 50

**Comment by indpurvesh** [comment]
did you change the site url or base url?

**Comment by gabrielkolbe** [comment]
No, I did not, just installed it.

**Comment by indpurvesh** [comment]
ok thanks i will try to replicate the bug. anyway thanks for raising the issue here @gabrielkolbe

**Comment by gabrielkolbe** [comment]
Well I know nothing of Laravel - still learning but it seems to me that if the session not there then on line 45 on website.php there is a query to the websitemodel does it get the wrong host, or website?

**Comment by gabrielkolbe** [comment]
aah, fixed it. I have installed the site on a domain called laravelcommerce. When I loaded the site it only worked on laravelcommerce/public, so I inserted the .htaccess file to reroot from laravelcommerce/public to laravelcommerce/ I had to make the change in the website - host column. voila!

**Comment by indpurvesh** [comment]
Thanks..  so i will close this issue. and once again thanks @gabrielkolbe
