### ISSUE TITLE
ErrorException in Website.php line 50:

### ISSUE THREAD

**Issue by technosolar** [mage2/laravel-ecommerce#17]
Trying to get property of non-object
/home/u250461069/laravel-ecommerce/vendor/mage2/framework/src/System/Middleware/Website.php#50

 }
        Session::put('website_id', $website->id);

        if ($website->is_default == 1) {
            Session::put('is_default_website', true);

**Comment by indpurvesh** [comment]
Hello @technosolar 

are you accessing website now from different url?

**Comment by technosolar** [comment]
not yet

**Comment by indpurvesh** [comment]
its fixed. 

https://github.com/mage2/framework commit no: 83

**Comment by technosolar** [comment]
... thank you ...
