### ISSUE TITLE
Error installing !

### ISSUE THREAD

**Issue by umercvision** [mage2/laravel-ecommerce#20]
QueryException in Connection.php line 770:
SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 3 (SQL: insert into `product_attributes` (`field_type`, `identifier`, `is_system`, `product_attribute_group_id`, `sort_order`, `title`, `type`, `validation`) values (TEXT, title, 1, 1, 0, Title, VARCHAR, required|max:255), (TEXT, price, 1, 1, 4, Price, FLOAT, required|max:8|regex:/^-FILE\d*(\.\d+)image$/), (1, 3, Image, FILE, , TEXT, sku), (1, 1, 2, SKU, VARCHAR, required|max:255, TEXT, slug), (1, 1, 1, Slug, VARCHAR, required|max:255|alpha_dash, TEXT, page_title), (1, 4, 0, Page Title, VARCHAR, max:255, TEXTAREA, page_description), (1, 4, 1, Page Description, VARCHAR, max:255, TEXT, qty), (1, 2, 2, Qty, VARCHAR, , CKEDITOR, description), (1, 1, 3, Description, TEXT, required, ?, ?))

**Comment by indpurvesh** [comment]
fixed and thanks @umercvision

**Comment by umercvision** [comment]
Thank you !
