### ISSUE TITLE
Table 'ecom.websites' doesn't exist (SQL: select * from `websites`)

### ISSUE THREAD

**Issue by Sagarbhagdev** [mage2/laravel-ecommerce#21]
when i write install in url i got this error
where my database name is ecom

QueryException in Connection.php line 770:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ecom.websites' doesn't exist (SQL: select * from `websites`)

**Comment by Sagarbhagdev** [comment]
if (!Schema::hasTable('migrations')) {
            return redirect()->route('mage2.install');
        }

remove it from comments and get solved

**Comment by Sagarbhagdev** [comment]
http://localhost:8000/install/database/table

now when i run this page i got error maximum execution time of 60 seconds exceeded

**Comment by Sagarbhagdev** [comment]
I have solved that both the errors but still while installation complete
its redirect to again installation page instead of admin login.

**Comment by Sagarbhagdev** [comment]
please solve that why its redirect again to install page
 and for solving max execution error you need to include 

ini_set('max_execution_time', 300);

at top of this file
 C:\xampp\htdocs\laravel-ecommerce\modules\base\Mage2\Install\route\web.php after solving this i got the problem of redirection so check it and try to fix it

**Comment by indpurvesh** [comment]
Because you un comment out  this line of code.

if (!Schema::hasTable('migrations')) {
return redirect()->route('mage2.install');
}

so leave the comment on it. it should be ok.

thanks
Purvesh

**Comment by Sagarbhagdev** [comment]
ok thanks man

**Comment by indpurvesh** [comment]
@Sagarbhagdev I have split the installation of migration into individual modules so i hope it wont do timeout now. I am closing this issue for now. Let me know if you still received this error?

**Comment by Sagarbhagdev** [comment]
okay, No Problem
