### ISSUE TITLE
Place Order - SQL Error

### ISSUE THREAD

**Issue by vafrcor** [mage2/laravel-ecommerce#22]
While tried to place the order, I have found this error.
<img width="1416" alt="screen shot 2017-01-20 at 4 34 43 pm" src="https://cloud.githubusercontent.com/assets/2148366/22143927/7345da08-df2e-11e6-8920-fc828a69ef88.png">

**Comment by indpurvesh** [comment]
@vafrcor thanks for :raising issue. i will fix the bug soon

**Comment by indpurvesh** [comment]
Let me know are you still getting error. But you have to reinstall the mage2 laravel ecommerce.
