### ISSUE TITLE
Demo site error

### ISSUE THREAD

**Issue by xiaolp** [mage2/laravel-ecommerce#25]
Demo site error

**Comment by indpurvesh** [comment]
thanks @xiaolp

**Comment by indpurvesh** [comment]
I just update the demo site but i have to add test data yet because as i have added product attribute feature almost ready so i have to generate new test data for this. Soon it will be available. Once again thanks @xiaolp

**Comment by Chinese1904** [comment]
@indpurvesh adding something to the cart throws an error as well.

**Comment by indpurvesh** [comment]
Just updated the demo site repository so it should be ok. thanks  to @Chinese1904  once again for helping and make the app better.
