### ISSUE TITLE
Unable to run application

### ISSUE THREAD

**Issue by mountstone** [mage2/laravel-ecommerce#27]
After installing, there are many errors while compilation clearing...

**Comment by indpurvesh** [comment]
@mountstone can you be more specific regards error? or is it possible to share some screenshot ?

**Comment by mountstone** [comment]
At the end of composer install, there is php warning:
```bash
php artisan clear-compiled
PHP Warning:  Declaration of Mage2\Framework\Foundation\Application::bootstrapPath() should be compatible with Illuminate\Foundation\Application::bootstrapPath($path = '') in /var/www/ecommerce/vendor/mage2/framework/src/Foundation/Application.php on line 6
The compiled services file has been removed.
```
When i go to app installation page, following error appears:
```bash
RuntimeException in Encrypter.php line 43:
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
```

Command:
```bash
php artisan key:generate
```
resolve this problem.

After login and go into categories page:
```bash
FatalThrowableError in DataGridManager.php line 49:
Type error: Too few arguments to function Mage2\Framework\DataGrid\DataGridManager::__construct(), 0 passed in /var/www/ecommerce/vendor/mage2/framework/src/DataGrid/DataGridManager.php on line 86 and exactly 1 expected
```

**Comment by indpurvesh** [comment]
Thanks it make sense I will solve it soon thanks for raising the issue @mou

**Comment by mountstone** [comment]
@indpurvesh 
Purvesh,

You are welcome to use and improve our brand new platform https://github.com/antaresproject

Based on Laravel, PHP7 ready, using flexible design patterns that keep the code clean and elegant.

I think it will be good idea to create your ecommerce platform as Antares Component

**Comment by indpurvesh** [comment]
@mountstone   Bug has been fixed. Thanks please install the dev-master again it should fix the problem.
