### ISSUE TITLE
ErrorException at http://demo.mage2.website/checkout

### ISSUE THREAD

**Issue by agsotelo** [mage2/laravel-ecommerce#29]
Hello, I just want to report an exception in you demo at http://demo.mage2.website/checkout. It throws an exception when I click the Checkout option:

```
ErrorException in a291b517d72834e382dd0d2b9c90edae4c8de36a.php line 258: Invalid argument supplied for foreach() (View: /var/www/demo/modules/base/Mage2/Checkout/views/checkout/new-index.blade.php)
```

PS: Great work. I will try out install it.

AugustoSL

**Comment by indpurvesh** [comment]
This bug should be fixed too. Thanks again for raising the issue.
