### ISSUE TITLE
Dumy data is not provided Unable to open home screen

### ISSUE THREAD

**Issue by jsvishaltrancis** [mage2/laravel-ecommerce#33]
When we open the screen , we get a fetal error
```
FatalThrowableError in FeatureProductHelper.php line 43:
Call to a member function attributeDropdownOptions() on null
```

Also unable to update any product for the product attributes 

Can u please provide some dummy data dump for the database

**Comment by indpurvesh** [comment]
If you do reinstall again from scratch it should fixed the issue for now. thanks for raising the issue here.

**Comment by jsvishaltrancis** [comment]
@indpurvesh  Can you add dummy data in tables during installation ?

**Comment by indpurvesh** [comment]
Yes currently working on dummy data installation and coupons code and reporting thanks
