### ISSUE TITLE
New Module

### ISSUE THREAD

**Issue by testpratap** [mage2/laravel-ecommerce#34]
how to add new module in this project

**Comment by indpurvesh** [comment]
Sorry but I haven't done documentation on it yet

**Comment by indpurvesh** [comment]
Just Adding a some basic level of documentation regarding hello world documnt.

**Comment by indpurvesh** [comment]
Check this page

[Mage2 Laravel Ecommerce Module](https://github.com/mage2/laravel-ecommerce/wiki/Mage2-Laravel-Ecommerce-Hello-World-Module)

**Comment by testpratap** [comment]
Thank's for reply
