### ISSUE TITLE
Error appear during product edit and extra attribute add

### ISSUE THREAD

**Issue by testpratap** [mage2/laravel-ecommerce#35]
Error appear during product edit. Please check the error

`Exception in ProductController.php line 169:
Error in Saving Product: Invalid argument supplied for foreach()`

Same error appears when we add an extra attribute to product

**Comment by indpurvesh** [comment]
currently working on it. thanks

**Comment by indpurvesh** [comment]
@testpratap bug has been fixed. Thanks once again.

**Comment by testpratap** [comment]
Thanks
