### ISSUE TITLE
error to install in page install/database/table 

### ISSUE THREAD

**Issue by mahdi4187** [mage2/laravel-ecommerce#41]
error to install in page (level Mage2 User) 
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'admin_password_resets' already exists (SQL: create table `admin_password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp not null) default character set utf8 collate utf8_unicode_ci engine = InnoDB)

**Comment by indpurvesh** [comment]
@mahdi4187 do you like to try re installation again.

**Comment by mahdi4187** [comment]
thank you

**Comment by indpurvesh** [comment]
@mahdi4187 I will close this issue. Please reopen if you found the issue again.
