### ISSUE TITLE
Class install does not exist

### ISSUE THREAD

**Issue by sangnguyenplus** [mage2/laravel-ecommerce#42]
Hi @indpurvesh,
I got this error when pulling the latest code.
![Screenshot](https://image.prntscr.com/image/U0ZzYD7XT4iZNs4gARBhAQ.png)
Please check it.
Thanks!

**Comment by indpurvesh** [comment]
This is the file it suppose to load. Can you try to find if file exist in your vendor/mage2/framewor/src folder

https://github.com/mage2/framework/blob/master/src/System/Middleware/Install.php

**Comment by indpurvesh** [comment]
@sangnguyenplus try composer update

**Comment by sangnguyenplus** [comment]
I'm updating vendor but I still stuck with `ext-pdo_sqlite` extension.
Thanks!

**Comment by indpurvesh** [comment]
You get it working??

**Comment by sangnguyenplus** [comment]
Yes, it's working now.
