### ISSUE TITLE
i have trouble at install database steps

### ISSUE THREAD

**Issue by duchungf9** [mage2/laravel-ecommerce#48]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'mage2-attribute' for key 'modules_identifier_unique' (SQL: insert into `modules` (`identifier`, `name`, `type`, `status`, `updated_at`, `created_at`) values (mage2-attribute, Mage2 Attribute, SYSTEM, ACTIVE, 2017-07-14 13:30:50, 2017-07-14 13:30:50))
--

**Comment by indpurvesh** [comment]
It should be fixed. Thanks
