### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [mage2/laravel-ecommerce#49]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - teamtnt/tntsearch v1.0.6 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.5 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.4 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.3 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.2 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.1 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - Installation request for teamtnt/tntsearch ^1.0 -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6].

  To enable extensions, verify that they are enabled in your .ini files:
    - D:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by indpurvesh** [comment]
It should be fixed. At this stage i am not doing Index based product search so yes i don't need this package.

**Comment by ZaheerAbbasAghani** [comment]
Here i went to php.ini and uncommend extension=php_pdo_sqlite.dll it statrted working
