### ISSUE TITLE
Error after installing database 

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [mage2/laravel-ecommerce#50]
SQLSTATE[HY000]: General error: 1 table "product_attributes" already exists (SQL: create table "product_attributes" ("id" integer not null primary key autoincrement, "title" varchar not null, "identifier" varchar not null, "field_type" varchar not null, "use_as_variation" integer not null, "is_system" integer not null default '1', "sort_order" integer null default '0', "created_at" datetime null, "updated_at" datetime null))

**Comment by indpurvesh** [comment]
Are you using version 1.7 ?
