### ISSUE TITLE
Stuck on table installation page

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [mage2/laravel-ecommerce#51]
![capture](https://user-images.githubusercontent.com/14222731/28248960-e0c4ac44-6a66-11e7-9b82-33ec65117e4b.PNG)

Click Continue to install Database it redirect me to this page
http://localhost:8000/install/database/table
and on this page i click Install next page it redirect me to same page . No idea where to go what to do ???

**Comment by indpurvesh** [comment]
It does create Module related database tables but just for debug purpose i am doing creating database table one after another rather then all in one click.

**Comment by ZaheerAbbasAghani** [comment]
thanks i thought i'll be created in one click .
