### ISSUE TITLE
Installing database error

### ISSUE THREAD

**Issue by DavidKrenekCZ** [mage2/laravel-ecommerce#55]
Hi, while installing database (Mage2 Related Product), I'm getting error:

_SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'related_products_id' doesn't exist in table (SQL: alter table `related_products` add constraint `related_products_related_products_id_foreign` foreign key (`related_products_id`) references `products` (`id`) on delete cascade)_

**Comment by indpurvesh** [comment]
it should be just related_product_id. Anyway i fix it up soon
