### ISSUE TITLE
nothing found after install 

### ISSUE THREAD

**Issue by terrauser1** [mage2/laravel-ecommerce#56]
**I do all three steps in my localhost but i don't know how to upload database and install all. i am new in laravel that why facing some basic problem.

please guide me step by process ...**

git clone https://github.com/mage2/laravel-ecommerce.git

composer update

mage2/laravel-ecommerce/.env

**Comment by indpurvesh** [comment]
@terrauser1 

Please follow this steps.

Step 1: Install Mage2 Commerce using Composer.

Run composer to create the lavender application:

composer create-project mage2/laravel-ecommerce --stability=dev
Set up your environment config file:

mage2/laravel-ecommerce/.env    

Create an empty Database using an phpmyadmin 
edit .env file and 
DB_DATABASE=MYDATABASENAME
DB_USERNAME=MYDATABASEUSERNAME
DB_PASSWORD=MYDATABASEPASSWORD

Step 2: go to url

Yoursite.com/install
That's it!

**Comment by terrauser1** [comment]
yes i do all this is my .env file

APP_ENV=local
APP_KEY=base64:8VLeJWzZz4XmdMuu5VZckZTT8f5H4HFnlJuetMvqfRI=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=forge
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=localhost
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_KEY=
PUSHER_SECRET=
PUSHER_APP_ID=

**Comment by terrauser1** [comment]
but after i run url - http://localhost/laravel-ecommerce/install

it go to not found page.

**Comment by indpurvesh** [comment]
you need to setup virtual host or try 

http://localhost/laravel-ecommerce/public/install

**Comment by terrauser1** [comment]
Thanx Purvesh,

one question how to remove public from url?

**Comment by indpurvesh** [comment]
Try google : how to create virtual host in Xampp or Wamp which ever server you been using it.

**Comment by indpurvesh** [comment]
Do Google Search: How to create a virtual host in Xampp or Wamp which ever server you been using it.

Please share it or star it here.
