### ISSUE TITLE
/install URL giving me db tables do not exist

### ISSUE THREAD

**Issue by jajajaime** [mage2/laravel-ecommerce#6]
There's no migration file to where setup the database, either. Am I missing something?

**Comment by indpurvesh** [comment]
Migration file is inside : Module/base/Mage2/Address/Database/Migration/

Give me some time i will do test and fix it up soon. 
Anyways thanks for creating issue: @jajajaime

**Comment by indpurvesh** [comment]
@jajajaime  bug is fixed.

**Comment by hotrush** [comment]
i am receiving 
```
QueryException in Connection.php line 763:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mage2.configurations' doesn't exist (SQL: select * from `configurations` where `configuration_key` = active_theme_path limit 1)
```
seems not fixed

**Comment by indpurvesh** [comment]
@hotrush  Actually it was my mistake that i commit wrong file. Anyway thanks for comment and i am in love with opensource project just because of you guy who raise the issue and help to improve the project. Thanks once again
