### ISSUE TITLE
Error in during installation

### ISSUE THREAD

**Issue by altafhussain10** [mage2/laravel-ecommerce#60]
Hello, 

When I try to install either by downloading from GitHub or composer, I get error 

```
Could not scan for classes inside "/Users/altaf/Sites/laravel-ecommerce/vendor/mage2/category/src/database" which
   does not appear to be a file nor a folder
```

This error is for all packages in the mage2 folder. 

I am using Valet 2.0.4 with php 7.0.20 and nginx 1.10.3

Can you please advice what is the problem here? 
Also check the attached screenshot.

<img width="827" alt="screen shot 2017-08-22 at 9 59 13 am" src="https://user-images.githubusercontent.com/4163772/29552584-a344f9b0-8720-11e7-9d1f-e5ede40364d8.png">

Thank you

**Comment by nestor-developing** [comment]
Hello,
I am having  same issue 
@indpurvesh please advice what is the issue?

![screenshot_10](https://user-images.githubusercontent.com/31207060/29561985-362af048-8755-11e7-87ab-47bdb516f594.png)

**Comment by aavriik** [comment]
Same problem here with runtime exceptions. Do we have any stable releases?

**Comment by chchluko** [comment]
Error, install from github and composer

[RuntimeException]                                                                                            
  Could not scan for classes inside "modules/mage2/feature/src/database" which does not appear to be a file or a folder

**Comment by indpurvesh** [comment]
It should be fixed. Thanks to all for your support.

**Comment by indpurvesh** [comment]
Error was inside composer.json file.

just Update: 

    "classmap": [
        "database/migrations" 
    ],
