### ISSUE TITLE
Migration error attribute schema/initial install errors

### ISSUE THREAD

**Issue by aavriik** [mage2/laravel-ecommerce#62]
From vendor attribute database migrations I assume.

![migration](https://user-images.githubusercontent.com/30973338/29612806-ab42c44c-8835-11e7-86ed-8413994e3e70.PNG)

**Comment by altafhussain10** [comment]
Same issue was happening to me. For a quick fix, I copied vendor/mage2/attribute/database folder to the root of my project and then ran the migration again, and it worked fine :)

**Comment by indpurvesh** [comment]
@altafhussain10 i think the problem is in the order migration running. to me it seems like a feature-product migration is running first then attribute -migration.
today i will fix this problem for sure. thanks to all for your help.

**Comment by indpurvesh** [comment]
Finally i found the bug. I will leave this open for now. Let me know if anyone has an issue again.

**Comment by aavriik** [comment]
I found another, it seems like the controller for the user home page doesn't exist.
![homecontroller](https://user-images.githubusercontent.com/30973338/29642315-b37e17d2-889a-11e7-96ec-afc36bbfe785.png)

**Comment by indpurvesh** [comment]
@aavriik  Thanks i have a look at this issue now.

**Comment by indpurvesh** [comment]
I just commited file. Let me know. thansk again for solving my bugs @aavriik

**Comment by aavriik** [comment]
Hi there, this is minor but in the InstallController administrator has a wrong spelling. 

Another question, are you in the process of changing the design/codebase right now? There are a few things missing in the pages like login/register buttons and a few bugs.

![magg](https://user-images.githubusercontent.com/30973338/29643346-1c99118a-88a1-11e7-866f-1719c5e9779e.png)


When I tried to access /register. It registers but it shows this error right after.
![localhost-8000-register](https://user-images.githubusercontent.com/30973338/29643426-aa8d620c-88a1-11e7-82b2-98e3747fc1ae.png)


And lastly checkout isn't working completely.


Thank you, I will test the application more.

**Comment by indpurvesh** [comment]
@aavriik I am not worried much about design. If you can do some design that would be so grateful.

Registration Error:  Local environment Email not able to send. 

I will double check on checkout page bug. and fix it up soon.

**Comment by altafhussain10** [comment]
@indpurvesh Yes I knew that, but I just posted a quick fix so others can use it until you fix the real problem. Thanks mate, you are doing a great job.
