### ISSUE TITLE
General error: 1005 Can't create table #sql-2278_1a1

### ISSUE THREAD

**Issue by zayngates** [mage2/laravel-ecommerce#63]
**General error: 1005 Can't create table `ngbaru`.`#sql-2278_1a1` (errno: 150 "Foreign key constraint is incorrectly formed")**

Hi, I got some problem after perform migration
Here detailed error

In Connection.php line 664:

  SQLSTATE[HY000]: General error: 1005 Can't create table `ngbaru`.`#sql-2278_1a1` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `product_storage` add constr
  aint `product_storage_product_id_foreign` foreign key (`product_id`) references `products` (`id`) on delete cascade)

In Connection.php line 458:

  SQLSTATE[HY000]: General error: 1005 Can't create table `ngbaru`.`#sql-2278_1a1` (errno: 150 "Foreign key constraint is incorrectly formed")

What is sql-2278_1a1 ?

**Comment by zayngates** [comment]
![screenshot_381](https://user-images.githubusercontent.com/22495187/30005602-435c5a8a-9110-11e7-8de8-dc6eb4b33349.png)

**Comment by indpurvesh** [comment]
fixed. thanks again
