### ISSUE TITLE
Class 'Mage2\Framework\Form\Form' not found

### ISSUE THREAD

**Issue by zayngates** [mage2/laravel-ecommerce#64]
Hi, I got some problem after install and access admin login.

C:\xampp\htdocs\devlabs\stage5\laravel-ecommerce\vendor\mage2\user-auth\src\Forms\LoginForm.php

![screenshot_382](https://user-images.githubusercontent.com/22495187/30019730-c157465e-918b-11e7-846a-692c5ff80d71.png)

**Comment by indpurvesh** [comment]
Thanks I will fix this tomorrow for sure
