### ISSUE TITLE
Error during installation.

### ISSUE THREAD

**Issue by shankhadevpadam** [mage2/laravel-ecommerce#66]
I have install the mage2 package, following the step in the readme but during the install  i get this error 
"RecursiveDirectoryIterator::__construct(/home/john/html/only_laravel_project/laravel-ecommerce/themes): failed to open dir: No such file or directory" and i have create the theme folder after that this error occur "Can't locate path: <>". How to solve this problem.

**Comment by indpurvesh** [comment]
if you create a just a dummy folder themes/CompanyName/ThemeName/register.yaml  it should be ok

**Comment by indpurvesh** [comment]
Fixed Bug Thanks @shankhadevpadam

**Comment by shankhadevpadam** [comment]
I got still error after creating the yaml file please provide me the dummy yaml file.

**Comment by indpurvesh** [comment]
@shankhadevpadam Bug has been fixed. So if you just do a 

    composer update


It should resolve the problem. Let me know if not.?

**Comment by shankhadevpadam** [comment]
Thanks now working.

**Comment by indpurvesh** [comment]
perfect
