### ISSUE TITLE
Registration Error.

### ISSUE THREAD

**Issue by shankhadevpadam** [mage2/laravel-ecommerce#67]
Type error: Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given,

**Comment by indpurvesh** [comment]
Are you having errors in front end?

**Comment by indpurvesh** [comment]
Do you want to do

    composer update

Then try again.? It might fixed the bug. I can't replicate bug in my system so please let me know.

**Comment by shankhadevpadam** [comment]
Yes i have got error in frontend. While i am trying to checkout.

**Comment by indpurvesh** [comment]
Fixed. Please do

    composer update

**Comment by shankhadevpadam** [comment]
[RuntimeException]                                                                                                            
  Could not scan for classes inside "/home/padam/html/only_laravel_project/laravel-ecommerce/vendor/mage2/category/database/fa  
  ctories" which does not appear to be a file nor a folder

**Comment by indpurvesh** [comment]
I think i remember that bug. sorry forget to commit. i do it now.

**Comment by indpurvesh** [comment]
try again.

**Comment by shankhadevpadam** [comment]
Thanks now working.

**Comment by indpurvesh** [comment]
Thanks @shankhadevpadam
