### ISSUE TITLE
Admin can't create category, product and user

### ISSUE THREAD

**Issue by luhegi** [mage2/laravel-ecommerce#7]
when create user and category return "FatalErrorException in FileViewFinder.php line 29:
Class 'Mage2\Framework\View\InvalidArgumentException' not found"
when create product return "ErrorException in cc72be8cceccff7e7ea896ecbcb691aca5141711.php line 22:
Undefined variable: statusOptions (View: C:\xampp\htdocs\laravel-ecommerce\modules\base\Mage2\Catalog\views\admin\catalog\product\boxes\basic.blade.php) (View: C:\xampp\htdocs\laravel-ecommerce\modules\base\Mage2\Catalog\views\admin\catalog\product\boxes\basic.blade.php):

**Comment by indpurvesh** [comment]
Hello @luhegi  bug should be fixed. 

Thanks for creating issue.
