### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by saularis** [mage2/laravel-ecommerce#70]
Will your ecommerce module run on Laravel 5.1? I was thinking if I change  "laravel/framework": "5.5.*" to  "laravel/framework": "5.1.*",

**Comment by indpurvesh** [comment]
@saularis simple answer is no. But If you really wanted to make it work for laravel 5.1 then you can manually you have to upgrade and follow the folder structure and copy and paste the codes.

**Comment by saularis** [comment]
@indpurvesh thanks
