### ISSUE TITLE
PHPUnit sqlite error

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#73]
Hello, I new here :)
After I got fresh install of this plugin, I've ran phpunit test.
Then I got an error `Database (/var/www/laravel-ecommerce/storage/database.sqlite) does not exist`

I found `laravel-ecommerce/storage/database_sqlite` file exists, so I changed it's name. Then it worked well.
I was curious why the name of file 'database_sqlite' is different from the file phpunit requires.

Anyway, I want to cheer you up until this plugin beat the other solutions :)

**Comment by indpurvesh** [comment]
should be fixed 

Thanks for raising this @darron1217
