### ISSUE TITLE
Class 'Form' not found error on view

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#74]
Whenever I try to enter product list page, this plugin emits the error below.

`Class 'Form' not found (View: /var/www/laravel-ecommerce/themes/mage2/default/views/catalog/product/view/product-card.blade.php) (View: /var/www/laravel-ecommerce/themes/mage2/default/views/catalog/product/view/product-card.blade.php)`

I guess `illuminate/html` was removed from core since 5.5.
So... please add alternative plugin `laravelcollective/html` on here :)

**Comment by indpurvesh** [comment]
It should be fixed now too. yes You are right about the duplicate Theme/Mage2- Default folder

Thanks @darron1217
