### ISSUE TITLE
Applying AdminLTE template

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#76]
https://github.com/almasaeed2010/AdminLTE
Yeah, AdminLTE is based on MIT License, so maybe we can utilize it for our fancy admin page :)
How do you think about it?

**Comment by darron1217** [comment]
https://github.com/acacha/adminlte-laravel
This can be a good example :)

**Comment by indpurvesh** [comment]
@darron1217  Thanks for the idea. I keep both in my mind. 

Initially i think about making a nice design too but then i think i don't want to waste much energy into design at this stage. Once i am able to add at least most basic level of features then i work on design in more details. Thanks again for your feedback.

**Comment by darron1217** [comment]
@indpurvesh  Thanks for consideration, too :)
I'm currently working with this issue, and I'll let you know if I succeed

**Comment by indpurvesh** [comment]
@darron1217 I think it wold be more great fully if you can help it on front end theme.

**Comment by darron1217** [comment]
@indpurvesh Hmm, sorry but I'm planning to apply paid theme, so I can't register it on github...

**Comment by darron1217** [comment]
https://github.com/jeroennoten/Laravel-AdminLTE
This is the best to apply 👍

**Comment by indpurvesh** [comment]
I am thinking to creating my own admin theme rather then depend on someone else. So thanks darron1217 i am closing this issue. Thanks you for your support
