### ISSUE TITLE
add .gitignore on /storage folder (for ignoring oauth-private.key files)

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#77]
![image](https://user-images.githubusercontent.com/8064923/31698607-37e5edae-b3f9-11e7-9f8d-cd8e94786d87.png)

After fresh install, `oauth-private.key` and `oauth-public.key` was included on git.
So... how about adding `.gitignore` file with *.key rule?

**Comment by indpurvesh** [comment]
i have to delete those file. Those file suppose to created automatic during installation process.

Thanks @darron1217  for bringing this to me.
