### ISSUE TITLE
Demo Admin Account

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#79]
Can you share account for admin page on demo site?

**Comment by indpurvesh** [comment]
its : Email : admin@admin.com
PW: admin123

But i have not updated demo website to latest version yet.

**Comment by darron1217** [comment]
@indpurvesh Yep :) Thanks

**Comment by darron1217** [comment]
@indpurvesh Does demo site account changed?

**Comment by indpurvesh** [comment]
@darron1217 Try now.

**Comment by darron1217** [comment]
@indpurvesh It works now :)
Thanks
