### ISSUE TITLE
AttributeController Error

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#80]
`Class 'Mage2\Attribute\Controllers\Admin\AdminController' not found`

![image](https://user-images.githubusercontent.com/8064923/31702588-e6e0b3fc-b412-11e7-99cf-05cec11f6ef0.png)

It is caused by namespace
https://github.com/mage2/laravel-ecommerce/blob/45dcd885a90973520847be4aba2c20f31943b6ad/modules/mage2/ecommerce/src/Http/Controllers/Admin/AttributeController.php#L25

This should be changed into 
```php
namespace Mage2\Ecommerce\Http\Controllers\Admin;
```

**Comment by indpurvesh** [comment]
This Feature is under development so not yet finished.

**Comment by darron1217** [comment]
@indpurvesh Okay I'll look forward to being updated :)
