### ISSUE TITLE
Place an order not working

### ISSUE THREAD

**Issue by shanuka** [mage2/laravel-ecommerce#81]
"Type error: Argument 1 passed to Mage2\Ecommerce\Events\OrderPlaceAfterEvent::__construct() must be an instance of Mage2\Order\Models\Order, instance of Mage2\E ▶"

**Comment by indpurvesh** [comment]
its on my list. But thanks again for raising most likes it might be fixed in tomorrow commit.

**Comment by indpurvesh** [comment]
it should be fixed.

**Comment by mdmaroof** [comment]
product is not adding to database on submitting database
