### ISSUE TITLE
wishlist in my account

### ISSUE THREAD

**Issue by mdmaroof** [mage2/laravel-ecommerce#84]
Wishlist is not removing from my account showing
 **`"Trying to get property of non-object"`**

**Comment by indpurvesh** [comment]
I will check and fix it tomorrow.

Just want to confirm you received the when you have click on remove from wishlist right?

**Comment by mdmaroof** [comment]
yes at the time of removing from Wishlist in my account

and also in admin panel order view status is not changing

**Comment by indpurvesh** [comment]
Both sound so simple bug to fix. I will do it tomorrow thanks for raising.

**Comment by indpurvesh** [comment]
Both bug should be fixed. @mdmaroof
