### ISSUE TITLE
admin template update issue

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#86]
I saw this fancy admin template at demo site.
![image](https://user-images.githubusercontent.com/8064923/32207332-95fb8d1e-be3e-11e7-99be-6b5c422d9682.png)

But, after fresh install at my server, I got 
![image](https://user-images.githubusercontent.com/8064923/32207349-b95a6258-be3e-11e7-9803-81c08c1fa695.png)

Is it a premium template?

**Comment by indpurvesh** [comment]
no it just a design that i am building it by myself.

**Comment by darron1217** [comment]
@indpurvesh Then... Is there a way to apply it? :)

**Comment by indpurvesh** [comment]
if you download the latest version and it should be ok

**Comment by darron1217** [comment]
@indpurvesh I got latest version just now. But it didn't change :(

**Comment by indpurvesh** [comment]
Have you try clear cache? 

    php artisan cache:clear

**Comment by darron1217** [comment]
@indpurvesh Yep I surely did it

![image](https://user-images.githubusercontent.com/8064923/32260587-1e369818-bf0c-11e7-919c-7adec426220a.png)

**Comment by darron1217** [comment]
@indpurvesh I cleared cache and it didn't work :(

**Comment by indpurvesh** [comment]
To me it seems like you are using version 1.8 rather then (dev-master) current development version.

**Comment by darron1217** [comment]
I've been always using 'dev-master'...
It's weird. Below is what I did yesterday.

1. Git Clone from repository (Of course, master branch)
2. composer update
3. create .env file
4. Followed Installation process at `mysite.com/install`
5. remove `mage2/install` from composer.json
6. Access to admin
7. old view is showing... :(

This is my current composer.json
![image](https://user-images.githubusercontent.com/8064923/32262217-c1a073c0-bf16-11e7-99b6-f3a07a5ea66d.png)

**Comment by smccoy78** [comment]
I am getting the same results as the op. I just did a fresh install yesterday. My mage2/install and mage2/module-installer are both "dev-master".

**Comment by indpurvesh** [comment]
@smccoy78  i will take a look at this bug.

**Comment by indpurvesh** [comment]
@smccoy78 Today i did a fresh installtion and i am getting a new bootstrap4 admin panel rather then old bootstrap3 admin panel. and same on front end i get a new bootstap4 theme too.

Do you want to try to install it into a new folder. It seems some weird kind a bug. I will dig deeper and try to find a cause.  thanks for your help

**Comment by darron1217** [comment]
@indpurvesh Now demo site also shows old theme of admin page....
How about re-opening this issue?

![image](https://user-images.githubusercontent.com/8064923/33592832-1af9556c-d9d0-11e7-90e0-132d213c4e6e.png)

**Comment by indpurvesh** [comment]
@darron1217 This is the new design using bootstrap4. 

Yes soon i will update and make a professional looking admin theme but in the mean time it stay like this.

**Comment by darron1217** [comment]
@indpurvesh I thought blue theme is the new one.... 
If then, mage2 admin was working perfectly since begging of this issue...
