### ISSUE TITLE
admin as a module

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#87]
This plugin has great module system :)

I wondered if there's a plan to make admin pages as module (to make it customizable)

This is an example from `aimeos-laravel`
![image](https://user-images.githubusercontent.com/8064923/32207454-5371f63a-be3f-11e7-9ada-b5233c5e29fa.png)

**Comment by indpurvesh** [comment]
once most feature gets developed then i will make all separate module and developer can create modules too.  take a look at the repository.

https://github.com/mage2
