### ISSUE TITLE
The way to develop theme

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#88]
Now I'm trying to apply my theme on this plugin :)

But I got no idea how this system works...haha

I guess creating documentation is ongoing, but I can't wait for it to be done...

I would be very nice if you tell me a way to create my own theme :)

**Comment by darron1217** [comment]
Okay, I found the code below.
Is it the right way to add path on config?

![image](https://user-images.githubusercontent.com/8064923/32220281-849eb0b0-be74-11e7-947d-b1a28cef34bb.png)

**Comment by indpurvesh** [comment]
Front end theme you just change:

    'paths' => [
        realpath(base_path('themes/vendor-name/theme-name/views')),
    ],
