### ISSUE TITLE
Providing Cart Items

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#90]
Will you allow us to use cart products on theme? :)

There's only count at current ViewComposer....
https://github.com/mage2/laravel-ecommerce/blob/dc333623244b587d5b61e3609d5e66210ec98070/modules/mage2/ecommerce/src/Http/ViewComposers/LayoutAppComposer.php#L43

into `$cart = Session::get('cart'); ` would be nice :)

**Comment by indpurvesh** [comment]
Yes inside any of your layout or balde file if you use

    $cartItems = Session::get('cart');

you will get collection of Cart Items
