### ISSUE TITLE
Category product filter is not implemented

### ISSUE THREAD

**Issue by darron1217** [mage2/laravel-ecommerce#91]
![image](https://user-images.githubusercontent.com/8064923/32306334-09b9ec2a-bfbe-11e7-9332-49c3c55d011a.png)

I want to know how to implement 'filter-box' which is already implemented on demo site :)
(I can't find it on current repository)

https://github.com/mage2/laravel-ecommerce/blob/a2896060883dc865b0c7cdbac625692641003d16/themes/mage2/default/views/catalog/category/options.blade.php#L18

**Comment by indpurvesh** [comment]
@darron1217 That feature doesn't work in this new database version. I am working on it but it will take some time.

**Comment by indpurvesh** [comment]
@darron1217 Category filter feature is almost finished. I am sure it should have many bugs so please try install again and let me know if you face any bugs.
