### ISSUE TITLE
Error while setting up project using mage2/framework 

### ISSUE THREAD

**Issue by harish-bisht** [mage2/laravel-ecommerce#93]
I am getting following error while setting up mage2 project using composer
`In Facade.php line 221:

  Call to undefined method Mage2\Framework\AdminMenu\AdminMenuBuilder::add()`

I am using mage2/framework in composer.json

**Comment by indpurvesh** [comment]
@harish-bisht 
Sorry to say but right now i have drop the idea of mage2/framewrok as a Laravel E commerce package. So you can't setup e commerce using any laravel project using mage2/framework.

Right now i am concentration on Mage2 E commerce App only. 

Thanks
Purvesh

**Comment by indpurvesh** [comment]
@harish-bisht 

Just an idea if you really want to use it in your existing Laravel Project. You can download and Put

    modules/ecommerc

as in your Laravel Project and then

open your composer.json and add line

    "Mage2\\Ecommerce\\": "src/"
    composer dump-autoload

then open config/app.php and add Provider class.

     Mage2\Ecommerce\Provider::class, 
     php artisan migrate


You might face a lot of troubles but it might work.

**Comment by harish-bisht** [comment]
thank you for the suggestion. 
While setting Mage2 E commerce project using composer method. it install correctly but it does not show many modules while  in demo admin it shows many features. What I am doing wrong? 
![mage2 e commerce](https://user-images.githubusercontent.com/12655090/32645131-9f3a5d04-c60b-11e7-8666-3a4eab1a9e73.png)

**Comment by indpurvesh** [comment]
@harish-bisht 

yes you right. Actually i haven't updated demo. 
Yes in previos version i have many features but in new one i am changing different database table structure and new file and folder arrangement.
So most features now comes with custom modules rather then framework feature. so i am currently working on making most basic feature for e commerce and custom module and theme features. But at this stage its not finished so i haven't done any documentation yet. But if you understand laravel then its not so hard to add custom feature.

**Comment by harish-bisht** [comment]
Thanks for prompt reply. 

How can I use module-installer in Mage2 E commerce? Also can I use module https://github.com/mage2/contact-us  and other modules?

**Comment by indpurvesh** [comment]
@harish-bisht  i think you can do it just by adding it to composer and it should work but i haven't test it yet.

**Comment by harish-bisht** [comment]
Can you give brief idea about the add custom feature. I want add few features in it as framework has.
I am ok in Laravel but not very good :)
