### ISSUE TITLE
bug mail and validate-quantity product

### ISSUE THREAD

**Issue by jabbatoyo** [mage2/laravel-ecommerce#95]
Hello,
I found a bug, when in the order view and send a SendEmailEnvoice, the following error appears: "the view 'mail.order.pdf'" not found
Solution: "mail.pdf".

I realized that when you create a product with quantity 2 and you enter as a standard user and add that product to your basket with an amount of 3 and the system accepts it, when it should not be possible to add a product of quantity 3 if the product in the database has quantity 2.

Greetings.

**Comment by indpurvesh** [comment]
@jabbatoyo  i have fixed the validate-quantity product. 
I will fix other bug soon too .thanks for raising bug.

**Comment by indpurvesh** [comment]
@jabbatoyo Bug - Mail is fixed too.

Thanks for raising bug.
