### ISSUE TITLE
object not found http://localhost:8080/laravel-ecommerce/install

### ISSUE THREAD

**Issue by vladbuich** [mage2/laravel-ecommerce#96]
could anybody help with project installation

**Comment by indpurvesh** [comment]
@vladbuich Can you take a screenshot and let me know some specific about the error you have received.
I just try in my local machine and it work perfectly fine.

**Comment by vladbuich** [comment]
@indpurvesh when i was installing using your notes
<img width="943" alt="2017-12-05 9 38 47" src="https://user-images.githubusercontent.com/24589835/33590311-3c1be4ba-d9a0-11e7-9276-07d57df637f1.png">
i had an error "object not found" going to http://localhost:8080/laravel-ecommerce/install
i suppose there is no install folder in project. you already have open issue with the same problem in 15 Oct

**Comment by indpurvesh** [comment]
@vladbuich  i am not sure but to me it seems something is wrong. 
You should have an install folder inside 
modules/mage2/install

 Can you confirm do you have this in your project?

**Comment by vladbuich** [comment]
yes, i have. is it the same?

**Comment by indpurvesh** [comment]
Yes
Which Php version you using it?

**Comment by vladbuich** [comment]
@indpurvesh 
<img width="464" alt="2017-12-05 10 01 50" src="https://user-images.githubusercontent.com/24589835/33590790-5e5e69e6-d9a3-11e7-944a-859d6e317931.png">

and what i have in modules/mage2/install
<img width="776" alt="2017-12-05 10 03 53" src="https://user-images.githubusercontent.com/24589835/33590857-acc9ae92-d9a3-11e7-83ce-f7214891ac96.png">

**Comment by indpurvesh** [comment]
It contains installation regarding code. 
And some sample database seed related files.

**Comment by indpurvesh** [comment]
If you can give me a screenshot of error would be perfect? Thanks for helping me to improve code base.

**Comment by vladbuich** [comment]
last picture shows what i have when go to http://localhost:8080/laravel-ecommerce/modules/mage2/install/

**Comment by indpurvesh** [comment]
I get it. It’s not a bug 

URL in browser should be: 

Http://localhost:8080/laravel-ecommerce/public/install

Try this url and it should work

**Comment by vladbuich** [comment]
got the same error "object not found"
what i have in public folder 
<img width="616" alt="2017-12-05 10 18 32" src="https://user-images.githubusercontent.com/24589835/33591164-ad09fc98-d9a5-11e7-98d9-f379d0b721a5.png">

**Comment by indpurvesh** [comment]
seems like your mod_rewrite is not enabled.

try this url:
http://localhost:8080/laravel-ecommerce/public/index.php/install

**Comment by vladbuich** [comment]
solved the problem by setting the access rights to the required folders

**Comment by vladbuich** [comment]
Thank you for your quick response
