### ISSUE TITLE
Copy/pasting too fast?

### ISSUE THREAD

**Issue by ReneKirk** [mage2/laravel-ecommerce#97]
Your license comments in the code contains:

` *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize **PrestaShop** for your
 * needs please refer to http://mage2.website for more information.
 *`

**Comment by indpurvesh** [comment]
@ReneKirk Thanks

**Comment by mauran** [comment]
https://github.com/mage2/laravel-ecommerce/blob/master/modules/mage2/ecommerce/src/Http/Controllers/WishlistController.php

```
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to http://mage2.website for more information.
```

**Comment by indpurvesh** [comment]
thanks @ReneKirk & @mauran
